import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/layout/Header";
import Contact from "../components/home/Contact";
import Footer from "../components/layout/Footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sahos Mia",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Contact />
        <Footer />
      </body>
    </html>
  );
}
